# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: llvm/llvm-project
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate VS project files
        run: cmake -S llvm -B build -G "Visual Studio 17 2022" -A x64 -Thost=x64 -DLLVM_ENABLE_DIA_SDK=ON
      - name: Build
        run: msbuild tools\llvm-pdbutil\llvm-pdbutil.vcxproj
      - name: upload build output
        uses: actions/upload-artifact@v2
        with:
          name: llvm-pdbutil
          path: build/Debug/bin/llvm-pdbutil.exe
